server:
  port: 8009

spring:
  main:
    allow-circular-references: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/public_examination_planet_schema?useUnicode=true&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    devtools:
      restart:
        enabled: true
        additional-paths: src/main
        exclude: static/**

alipay:
  # 支付宝appId
  appId: 9021000134649028
  # 应用私钥
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCinsDSnfCkcfOyPvzU6gTQKYmpSG69FZUTl1ilqf39xf3eCzPdjHZbCCeE+sXs9YAMAG+yekheosRYKtRD3ROkNfAPzMGpFKVWMbJxUeVKmBQoWAEP19eDq276PTt9jh/dfIz0D802xD0OphIzGyBVcMiPuojCnv0bqAbDsRXUd32pXf6jWr9lwzDjeF8Ua9oqQr/CO/WPAEYaxMZJaooPOCC6ITOkSHhOk0iGhEI7/BEUFbNkrEXpFdsOG6VfD1P3hcMkGbUY4CRiTctvN/FKrKbN2oRDiMXZmY9nAb6u7gxfuJbWm7FdiYrukV5Mx0mfg8PneZ7CQsrHEW1kXP+vAgMBAAECggEAOU3j+NP7FpepHmifw49rfscEYYjKrQrL64lrjYUnoaOBYBtmfW2fz1hCRNPxpxyjsJb+xU/d7KtCsSb2gauH3le7bnXi0GgcExGUJeaL/As3HzhTt3eB1D427ytgqU/J3syjBuYClIf2VBElXKj0bec+ZZd/1cUcwAAn0hG29ZVNwknd5ip2ETF4RUkgaduMOAE1c1PA0fzfdP911z/HsttYiW16FrALdXj/Y1MfwIx1URlH/JhwBTfsOK7kDFbuEx5M9xS+ScCO53KvE9zgUyso5nkplD9/w6z+i9FJtABX7bSqdV70gK7YhuhG9CDyCxp52a3UyNM2XQyuCorYgQKBgQDYNrGWlnRTyW5DkW2aNHsM6kAuPxWDVFHycWfWS3j/vQJlyAhDG1WfrjnA7bGRfgF2fFBcgo/YS7USJBZijlQStS3PvwbnTyJckmbwXpNcsTiByuvPjA+yoDjKgXM8zbNJpCudcK12/bgsXfBMLdfm4AeQu084xfvrSwquOCP0oQKBgQDAi2W/bEtymR9H7AVt6X8W8u4thLusL2ZS7m92ZwM4v+s+seoTt6NA2qcHAYFbolSM1H0TENdcahlQaXy6eg6cSipeJsc7gNBfxFsLUtgDbZWe87NmX59XQGtz5lWfrzwuK03rkEKWVy29TRygj22ZX/35Wcuo41XYzu56/FNCTwKBgCXjD6Nvodq8xVGZvjbzU0ykD7MK4t4sfF+bd7KZbw6BNFZZgvkfZRWiFgS0ohT4m5EDn6FWT5Z7TbNsF3AVuK2+idSJiNAnkcHe9aLRL8liVKCJymCIDogig1EY9fSFpxEUb4AbKopbU1aS73Sp49dVEn5OFEfCia5la+2zcLmBAoGAOaMAyDaAt0NC6+KpFWfKFXKO/a04CKj/tl+NmiHoAvrgTpovecuE4QsS6LP4pxeGu8l3z1dBQHa6MSoCnkefTAWffSOajCNZPPGoV1FrPEt3eGd3EnQZXKL6B22xv+VS3Hc2EgfTBvH9zSbiJOYKZtknS5cnsdyrfAUlukcCHV0CgYEAlqNR9mYSJLWBn7nT7lPTDkLqvPU4a3Rq13amWxSRkG5aQDQ181ikWm7fD0ki7xCc3TZVf1R1ppBfHka8g6ZUfs34WaWijZcp3deUi+1wSmUub3Z1HIjihDFAfDqKjPwbO8LZI1qgkypBhYeWlns8unbUHKoDVt1nx32L2HhPBlk=
  # 支付宝公钥
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkvZoSjczVp+QHV97KjUnYt/xVkknXl4uM1p0NFs4PjlC8Lqsl5uYdRWHPk9QXdYjHWFuYWTA+JZFFlkypzREhk4zM5+AXsIztuwUV9cFlBKcF3vGK3mR1lNiaM8Ea7nEVC3ulDTQ36q/A8BQvksdnhhKsvtph47m813upWCFxyPb7nvDD34R8mQkGwpI/QclDTBrbULcZKojHHRlUHl1RTXUwGYOy8O4IK338MUreiXMP7eBYhq21Jd9c9FKR0itSJLsAGAv3EM4vgDmRkq/bNB9plfKWIWlwEefx39lKxF9Inl18xENR2blw2wRFmfqTtyi1m+BSt/DZLh/Ni6c/wIDAQAB
  #支付宝通知本地的接口
  notifyUrl: http://pqdtfs.natappfree.cc/alipay/notify
  #支付宝回调地址
  returnUrl: http://localhost:5173/base/manage/myOrderOfManage
  returnUrl2: http://localhost:5173/starter/login

live-room:
  open-live:
    #直播服务器推流地址
    server-address: rtmp://192.168.159.134:1935/live/
    #直播前端播放器拉流地址
    flv-url: http://192.168.159.134:8080/live/

files:
  imageUpload:
    path: D:\Desktop\public_examination_planet_\public_examination_planet_images
  videoUpload:
    path: D:\Desktop\public_examination_planet_\public_examination_planet_videos